slack:
  save:
    messages: false
    events: false
    commands: false
    actions: false
  refresh:
    user: 3600
    channel: 3600
  endpoints:
    commands: "/slack/commands"
    actions: "/slack/actions"
  plugins:
    - sirbot.slack.example
